---
title: "Hypothesis Tests"
author: "Landi Luo"
date: "12/7/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages:
```{r, message=FALSE}
if (!require("pacman"))  
  install.packages("pacman", repos = "http://cran.us.r-project.org/")
p_load("tidyverse", "survival", "kableExtra")
```

Import data:
```{r}
breast <- readRDS(file = "breast_final.rds")

# delete all survival time = 0
breast <- subset(breast, SRV_TIME_MON != 0)

# convert SEX to dummy: 0=male, 1=female
breast$SEX <- ifelse(breast$SEX == 1, 0, 1)
```

## Log Rank test (from Joowon's code)
```{r}
log.rank = function(time, event, data, list){ # list : number of selected column
  surv = Surv(time, event, type = "right")
  result = data.frame("Log-rank_p" = NA, "Gehan_p" = NA)
  
  for (i in 1:length(list)){
    cova = data[,list[i]]
    surv.test = survdiff(surv ~ cova, rho = 0)
    surv.test2 = survdiff(surv ~ cova, rho = 1)
    result = rbind(result, round(c(1-pchisq(as.numeric(surv.test[5]),length(unique(cova))-1), 1-pchisq(as.numeric(surv.test2[5]),length(unique(cova))-1)),4))
  }
  
  result = result[-1,]
  result = data.frame("variable" = colnames(data)[list], result)
  rownames(result) = 1:nrow(result)
  result
}

breast = data.frame(breast)
logrank_table <- log.rank(time = breast$SRV_TIME_MON, event = breast$delta, data = breast, list = c(1,3,4,6,12:15))

kable(logrank_table, "latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "striped")

breast_final2 = breast
breast_final2$Agemean = as.integer(breast$Age>mean(breast$Age))
breast_final2$AgeDXmean = as.integer(breast$Age>mean(breast$AGE_DX))

logrank_table2 <- log.rank(time = breast_final2$SRV_TIME_MON, event = breast_final2$delta, data = breast_final2, list = c(1,3,4,6,12:17))

kable(logrank_table2, "latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "striped")
```

## LRT, Score, Wald Tests


```{r}
single.cox = function(time, event, covariate, co.type) {
  
  p1 = p2 = p3 = c()

  for (i in 1:ncol(covariate)){
    surv.sub = Surv(time=time, event=event, type="right")
    if (co.type[i]=="N") { # continuous variable
      formul = paste("surv.sub ~ covariate[,", i, "]", sep="")
      fit = coxph(eval(parse(text=formul)), ties = "breslow")
    } else { # categorical variable
      formul = paste("surv.sub ~ factor(covariate[,", i, "])", sep="")
      fit = coxph(eval(parse(text=formul)), ties = "breslow")
    }
    p1 = rbind(p1, t(round(summary(fit)$waldtest, 3))) # Wald Test
    p2 = rbind(p2, t(round(summary(fit)$sctest, 3))) # Score Test
    p3 = rbind(p3, t(round(summary(fit)$logtest, 3))) # LRT
  }
  
  result = list()
  result[[1]] = p1 ; result[[2]] = p2; result[[3]] = p3
  return(result)
  
}

##---------------------

# Example
co.type = c(rep("C", 4), rep("N", 2), "C", rep("N", 2), rep("C", 4)) # "C" means categorical variable / "N" means numeric variable
X = breast[,-c(2,5)] # covariate
result = single.cox(time = breast$SRV_TIME_MON, event = breast$delta, covariate = X, co.type)
names(result) = c("Wald Test", "Score Test", "LRT")
rownames(result[[1]]) = colnames(X); rownames(result[[2]]) = colnames(X); rownames(result[[3]]) = colnames(X)
wald <- data.frame(result$`Wald Test`)
score <- data.frame(result$`Score Test`)
lrt <- data.frame(result$LRT)

kable(wald, "latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "striped")

kable(score, "latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "striped")

kable(lrt, "latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "striped")
```

